name: eslint
on: pull_request
jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: ESLint checks
        uses: gimenete/eslint-action@1.0
        with:
          github_token: ${{ secrets.github_token }}
