name: main

on:
  pull_request:
  push:
    branches: [master]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v1

      - name: set PY
        run: echo "::set-env name=PY::$(python --version --version | sha256sum | cut -d' ' -f1)"

      - uses: actions/cache@v1
        with:
          path: ~/.cache/pre-commit
          key: pre-commit|${{ env.PY }}|${{ hashFiles('.pre-commit-config.yaml') }}

      - uses: pre-commit/action@v1.0.1

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Read .nvmrc and pass it on
        run: echo ::set-output name=NVMRC::$(cat .nvmrc)
        id: nvm

      - name: Setup node w/ nvm version
        uses: actions/setup-node@v1
        with:
          node-version: '${{ steps.nvm.outputs.NVMRC }}'

      - name: yarn install w/ cache
        uses: bahmutov/npm-install@v1

      - name: Run ESLint and TSC type check
        run: yarn lint

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Read .nvmrc and pass it on
        run: echo ::set-output name=NVMRC::$(cat .nvmrc)
        id: nvm

      - name: Setup node w/ nvm version
        uses: actions/setup-node@v1
        with:
          node-version: '${{ steps.nvm.outputs.NVMRC }}'

      - name: Install yarn w/ cache
        uses: bahmutov/npm-install@v1

      - name: Run all tests
        run: yarn lerna run test

  publish:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    needs: [pre-commit, lint, test]

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Install Packages
        run: yarn install --frozen-lockfile

      - name: Test
        run: yarn test

      - name: Authenticate with Registry
        run: |
          yarn logout
          echo "@slack-wrench:registry=http://registry.npmjs.org/" > .npmrc
          echo "registry=http://registry.npmjs.org/" >> .npmrc
          echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> .npmrc
          npm whoami
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish with Lerna
        run: yarn build && yarn lerna:publish --yes
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
