name: publish

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Configure CI Git User
        run: |
          git config --global user.name '@tteltrab'
          git config --global user.email 'tteltrab@users.noreply.github.com'
          git remote set-url origin https://$GITHUB_ACTOR:$GITHUB_PAT@github.com/IBM/slack-wrench.git
        env:
          GITHUB_PAT: ${{ secrets.GITHUB_PAT }}

      - name: Install Packages
        run: yarn install --frozen-lockfile

      - name: Test
        run: yarn test

      - name: Authenticate with Registry
        run: |
          yarn logout
          echo "@slack-wrench:registry=http://registry.npmjs.org/" > .npmrc
          echo "registry=http://registry.npmjs.org/" >> .npmrc
          echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> .npmrc
          npm whoami
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish with Lerna
        run: yarn build && yarn lerna:publish --yes
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
