name: yarn

on:
  pull_request:
  push:
    branches: [master]

jobs:
  yarn:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Read .nvmrc
        run: echo ::set-output name=NVMRC::$(cat .nvmrc)
        id: nvm
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: '${{ steps.nvm.outputs.NVMRC }}'
      - uses: Borales/actions-yarn@v2.1.0
        with:
          cmd: install # Yarn command
      - uses: Borales/actions-yarn@v2.1.0
        with:
          cmd: test # Yarn command
